name: Deploy Terraform to AWS

on:
  push: 
    branches: 
        - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0 

      - name: Generate RSA Key Pair
        run: |
          ssh-keygen -t rsa -b 4096 -f ./runner-server.key -N "" 
          # Store the public key as an artifact or secret if necessary
          echo "Public key generated"
      
      - name: Upload SSH Key
        run: |
          echo "Public Key: $(cat ./runner-server.key.pub)"

      - name: Create Terraform variable file
        run: |
          cat <<EOF > terraform.tfvars
          docdb_password="${{ secrets.DOCDB_PASSWORD }}"
          docdb_user="${{ secrets.DOCDB_USER }}"
          NRP_core_token="${{ secrets.NRP_CORE_TOKEN }}"
          NRP_web_token="${{ secrets.NRP_WEB_TOKEN }}"
          EOF
          echo "Terraform variable file created"
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy (optional)
        run: terraform destroy -auto-approve
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan